[package]
name = "greetings"
version = "0.0.1"
authors = ["Paul Ehrhardt <ehrpaulhardt@gmail.com>"]

[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.5", default-features = false }

[lib]
crate-type = ["dylib"]